baseURL: 'https://anmarivanderwesthuizen.com/'
title: Anmari van der Westhuizen

params:
  languageCode: en-za
  author: Anmari van der Westhuizen
  copyright: Anmari van der Westhuizen
  description: Anmari van der Westhuizen is one of South Africa's leading cellists. She lectures at the University of the Free State, plays in the Odeion String Quartet, and often conducts orchestras and teaches masterclasses.
  designer: Paul Joubert
  logo: /images/logo.png
  images:
  - /images/cover.jpg

menu:
  main:
  - URL: /about
    name: About
    weight: 1
  - URL: /calendar
    name: Calendar
    weight: 2
  - URL: '/#info'
    name: Media
    weight: 3
  - URL: '/#contact'
    name: Contact
    weight: 4
