baseURL: 'https://anmari.netlify.app/'
languageCode: en-us
title: Anmari van der Westhuizen

menu:
  main:
    - URL: /about
      name: About
      weight: 1
    - URL: /calendar
      name: Calendar
      weight: 2
    - URL: '/#info'
      name: Media
      weight: 3
    - URL: '/#contact'
      name: Contact
      weight: 4
