baseURL: 'https://anmari.netlify.app/'
languageCode: en-us
title: Anmari van der Westhuizen

menu:
  main:
    - URL: blog
      name: Blog
      weight: 1
    - URL: pricing
      name: Pricing
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
    - URL: faq
      name: FAQ
      weight: 4
